version: '3.1'
services:
  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: pass

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: pass
  #     ME_CONFIG_MONGODB_URL: mongodb://admin:pass@mongo:27017/

  server:
    build: .
    command: "npm run dev"

    environment:
      PORT: 8000
    
    volumes:
      - .:/server
    ports:
      - "8000:8000"
 # Port required for debugging with node
      - "9229:9229"
   
volumes:
  db: {}
 